### ISSUE TITLE
TypeError: Failed to fetch dynamically imported module: http://192.168.1.61/assets/index-DX0II4F7.js

### ISSUE THREAD

**Issue by Fabberlaan** [raspiblitz/raspiblitz-web#736]
TypeError: Failed to fetch dynamically imported module: http://192.168.1.61/assets/index-DX0II4F7.js

Please report this error to https://github.com/cstenglein/raspiblitz-web/issues

Stack trace:

at pr (http://192.168.1.61/assets/index-C20ev6OT.js:102:7778) at lr (http://192.168.1.61/assets/index-C20ev6OT.js:73:30630) at Suspense at yv (http://192.168.1.61/assets/index-C20ev6OT.js:64:3910) at Lv (http://192.168.1.61/assets/index-C20ev6OT.js:64:7686) at Z_ (http://192.168.1.61/assets/index-C20ev6OT.js:102:13280) at L1 (http://192.168.1.61/assets/index-C20ev6OT.js:73:29584) at E1 (http://192.168.1.61/assets/index-C20ev6OT.js:73:27785) at Cv (http://192.168.1.61/assets/index-C20ev6OT.js:64:7071) at Dv (http://192.168.1.61/assets/index-C20ev6OT.js:73:892) at Y_ (http://192.168.1.61/assets/index-C20ev6OT.js:102:15031) at o (http://192.168.1.61/assets/index-C20ev6OT.js:73:26961)

**Comment by cstenglein** [comment]
This is related to  #718
